### ISSUE TITLE
💡 feat [upload]: add dropzone

### ISSUE THREAD

**Issue by kilchenmann** [av-dimag/ech-0160-dimag-ingest#24]
### Start Date

2023-02-06

### Summary

![start-open-sip](https://user-images.githubusercontent.com/4253580/216355192-e378187d-5d8e-4059-b27e-0ed4de8fc3db.png)

### Tasks / To do

- [x] Öffnen/Laden eines ZIP files in Electron
- [x] Startseite beinhaltet grosse Ladezone mit:
  - [x] Drag'n'Drop-Funktion
  - [x] Klick öffnet Öffnen-Dialog
- [x] Zip im Hintergrund "ablegen" --> temporärer Ordner
- [x] Nach dem Öffnen/Laden verschwindet die Ladezone

### Unresolved questions

In einem weiteren Schritt muss das Hochgeladene Paket überprüft werden. Dies erfolgt in einem separaten Task
