### ISSUE TITLE
💡 feat [dialog]: general message box

### ISSUE THREAD

**Issue by kilchenmann** [av-dimag/ech-0160-dimag-ingest#34]
### Summary

Neue Komponente (Dialog), um Fehlermeldungen anzuzeigen. In der Regel benötigen wir einen Message-Service, der Fehler oder allgemeine Hinweise darstellen kann. 
@Input: Titel, Nachricht, Log (opt)

<img width="640" alt="error-msg" src="https://user-images.githubusercontent.com/4253580/216617622-d373d4f6-9469-4375-9d03-088547f7ee29.png">

Inspiration von
https://pencilandpaper.io/articles/ux-pattern-analysis-error-feedback/

### Tasks / To do

- [x] Neue Komponente mit @Input Msg: {title, msg, log}
- [x] Dialog-Box Integration https://material.angular.io/components/dialog/overview
- [x] Simple Anpassung am Style

### Unresolved questions

Benötigen wir noch mehr Infos im Msg Interface?
Macht Dialog-Box Sinn?
