### ISSUE TITLE
💡 feat [validation]: check eCH-0160

### ISSUE THREAD

**Issue by kilchenmann** [av-dimag/ech-0160-dimag-ingest#36]
### Summary

Überprüfe ob der Inhalt des ZIP-Files einem ech-0160 entspricht.

### Tasks / To do

- [x] Zip entpacken oder direkt lesen
- [x] Ordner `content` und `header` vorhanden und beide nicht leer
- [x] File `header/metadata.xml` vorhanden
- [x] File `header/metadata.xml` valid --> bereits im Ingest-POC vorhanden

### Reference Issues or PRs

Erfolgt nach #35 im Zusammenhang #24
