### ISSUE TITLE
💡 feat [organize]: Display content 

### ISSUE THREAD

**Issue by kilchenmann** [av-dimag/ech-0160-dimag-ingest#48]
### Summary

Nach dem Öffnen des ZIPs erfolgt das Lesen des `header/metadata.xml`-Files. Mit diesen Daten kann der Inhalt von `content/`, sowie einzelner Dateien dargestellt werden. Dies wurde bereits im Ingest-POC im Rahmen der Library umgesetzt.

Hinzu kommt jedoch neu die Ansicht der generierten AIPs auf der rechten Seite. Die zwei Teile (SIP links und AIPs resp. Ingest Pakete rechts) können mit [angular-split](https://angular-split.github.io/) getrennt und variabel in der Breite dargestellt werden.

![image](https://user-images.githubusercontent.com/4253580/218115412-a0f22d4e-7a4a-40c8-ac4b-a863bf516854.png)

![image](https://user-images.githubusercontent.com/4253580/218115327-2dd82d32-62ce-465e-91e1-470ae47f5726.png)

### Tasks / To do

- [x] Angular-split hinzufügen `yarn add angular-split`
- [x] Inhalt, Ablieferung und Header mit matTabs darstellen (wie bereits im Ingest-POC vorhanden)
- [x] Metadaten und Inhaltsbaum auflisten (wie bereits im Ingest-POC vorhanden)

### Drawbacks

~Überlegungen zum Platz müssen gemacht werden. Wie sieht der nächste Schritt aus? Wie oder wo werden die Ingest Pakete später dargestellt?~ --> wie angedacht auf der rechten Seite.

### Unresolved questions

~Wo sollen die Metadaten einer einzelnen Datei dargestellt werden? Aus Platzgründen kann es nicht mehr auf der rechten Seite dargestellt werden.~ --> Mit Angular-Split könnte dies relativ elegant gelöst werden.
