### ISSUE TITLE
💡 feat [routing]: define routes for the steps in the workflow 

### ISSUE THREAD

**Issue by kilchenmann** [av-dimag/ech-0160-dimag-ingest#51]
### Summary

Die Bereiche "upload/open" und "organize" sollten eigene Routen haben, um die Seiten später einfacher anzusteuern. Die Route "/organize" wird ergänzt durch eine ID des aktuell zu bearbeitenden Pakets/SIPs. 
Der dritte Bereicht "Export" erhält vorerst keine eigene Route, da dies ein Teil von "organize" sein wird.

### Tasks / To do

- [x] neue Route "/upload"
- [x] neue Route "/organize/[sip-id]"
- [x] Die Startseite "/" leitet direkt auf "/upload" um

**Comment by janicklg** [comment]
Braucht es die SIP-Id in der 'organize' Route? Falls man nur ein File jeweils hochladen und dann bearbeiten kann, bräuchte es keine zusätzliche ID.
