### ISSUE TITLE
💡 feat [organize]: display ingest packages

### ISSUE THREAD

**Issue by kilchenmann** [av-dimag/ech-0160-dimag-ingest#53]
### Summary

Auf der rechten Seite kann man nach dem Auswählen der einzelnen Ordner (wahrscheinlich über den vorhandenen Button "Export als AIP") die Ingest Pakete mittels [Material Expansion Panel](https://material.angular.io/components/expansion/overview) darstellen.

![image](https://user-images.githubusercontent.com/4253580/218133266-71b54b68-52b7-4d01-972b-1282e1152d3f.png)

### Tasks / To do

- [x] Expansion Panel Modul hinzufügen
- [x] Klick Event des vorhandenen Buttons "Export als AIP" umschreiben: Paket Info (Ordnername und zugehörige Files) an Komponente rechts senden.
- [x] Pakete in der Expansion Liste darstellen: Ordnername als Titel und Auflisten der einzelnen Files

**Comment by janicklg** [comment]
Frage @kilchenmann / @lws2014 --> Habe ich folgendes richtig verstanden:

Für jeden Ordner, welcher Dateien enthält soll ein Ingest Paket gemacht werden oder?

Beispiel:
* Ordner POC-Test
  * Datei 1
  * Ordner Ressourcen
    * Ordner Finanzen
      * Datei 1
      * Datei 2  
     * Ordner Personal
       * Ordner Kontaktdaten
         * Datei 1
         * Datei 2  
         * Datei 3


Daraus wären es dann die Ingest Pakete:
* Ordner POC-Test (mit 1 Datei)
* Ordner Finanzen (mit 2 Dateien)
* Ordner Kontaktdaten (mit 3 Dateien)

Aus dem Ordner 'Ressourcen' und 'Personal' würde kein Ingest Paket gemacht werden, da sie keine Dateien beinhalten oder?

------------------------------------------------------------------------------------------------------------------------

Ist das Beispiel korrekt oder sollten die einzelnen Ingest Pakete anders erstellt werden?

**Comment by lws2014** [comment]
Ich weiss nicht genau was @kilchenmann für den Prototypen vorgehehen hat. Es gibt verschiedene Möglichkeiten:
1. Erstellen von einzelnen Paketen von allen vorhandenen Ordner mit Content
2. Erstellen von einzelnen Paketen von ausgewählten Ordnern mit geflattetem Content
3. Eine Kombination von beidem.

Die zweite Variante scheint mir sinnvoll für den Prototypen, die dritte am flexibelsten aber allenfalls für den Prototypen ein Overklill. Hier trotzdem ein möglicher Vorschlag dazu:

![230216-ui1 ](https://user-images.githubusercontent.com/7768615/219340649-4182d52a-aa53-4778-9ae7-e76e67744c17.png)
