### ISSUE TITLE
💡 refactor [code]: refactor code and resolve to dos

### ISSUE THREAD

**Issue by janicklg** [av-dimag/ech-0160-dimag-ingest#57]
### Summary

Mit diesem Ticket sollte der Code refactored und to do's erledigt werden.

Folgende Punkte sollte man überprüfen und falls möglich direkt erledigen:

### Tasks / To do

- [ ] Grosse / shared Funktionen in Service auslagern
- [ ] To do's im Code suchen und erledigen (oder neues Ticket erstellen)
- [ ] Überprüfen, ob bestimmte Funktionen einfacher gemacht werden können
- [ ] Alle Funktionen kommentieren
- [ ] Naming überprüfen (z.B kommt viel der Begriff 'ingestPackage' oder 'node' vor -> wie wollen wir was benennen?)
- [ ] Console.log's entfernen
- [ ] Prüfen, ob man bestimmte Interfaces / Konstanten mehrmals definiert
- [ ] Unused Code / Komponenten (z.B Playground) entfernen
