### ISSUE TITLE
💡 feat [design]: resolve styling issues

### ISSUE THREAD

**Issue by kilchenmann** [av-dimag/ech-0160-dimag-ingest#61]
### Summary

Kleine Styling issues ausbessern; u.a. Scroll-Bereiche (s. Screenshot), Responsive Design, Mat-Card beim Upload

### Tasks / To do

- [ ] `overflow: none` im Hauptbereicht
- [ ] `mat-card` im upload entfernen
- [ ] `padding-left` im header von package-expansion-panel 
- [ ] evt. responsive design im upload; evt. auch im Zusammenhang scroll area

**Comment by kilchenmann** [comment]
Aktuell sieht die APP so aus:

![Screenshot 2023-03-07 at 17 08 10](https://user-images.githubusercontent.com/4253580/223480042-eeabffb4-3a73-4dd8-9abb-74a64d068533.png)

Es fehlt nun noch die Höhenanpassung im Organize, damit die Scrollbalken korrekt sind. Vorschlag: Scrollen nur innerhalb des Tab-Contents

**Comment by kilchenmann** [comment]
@janicklg soeben (7fe4e7d) habe ich auch die Scroll-Problematik im Bereich "organize" gelöst. Bin aber noch nicht zu 100% zufrieden. Auf der rechten Seite ist etwas noch nicht ganz sauber. Aber wenn Du Zeit hast, kannst Du ja mal den entsprechenden PR anschauen...
