### ISSUE TITLE
💡 feat [test]: write unit tests

### ISSUE THREAD

**Issue by kilchenmann** [av-dimag/ech-0160-dimag-ingest#79]
### Summary

Wir sollten pro Komponente und Service mindestens 1-2 Testeszenarien ausdenken und entsprechende unit Tests (.spec.ts) schreiben.

### Tasks / To do

Bspw. 
- [ ] ZIP hochladen und prüfen
  - [ ] ZIP Validität
  - [ ] eCH-0160 Validität
- [ ] xml 2 json Tests und Darstellung prüfen
- [ ] Ingest Pakete auf Inhalt testen
- [ ] Export metadata.xml-Ergebnis testen

### Unresolved questions

Wahrscheinlich muss dieser Issue in einzelne Tasks aufgeteilt werden.
